version: "3.9"

services:
  postgres_db:
    image: postgres:15
    container_name: motor_plascencia_db
    environment:
      POSTGRES_DB: atoms_db
      POSTGRES_USER: maestro_aluminero
      POSTGRES_PASSWORD: password_seguro123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app_taller:
    build: .
    container_name: taller_app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    command: streamlit run app_taller/produccion.py
    depends_on:
      - postgres_db

  app_oficina:
    build: .
    container_name: oficina_app
    volumes:
      - .:/app
    ports:
      - "8502:8502"
    environment:
      - PYTHONPATH=/app
    command: streamlit run app_oficina/alimentador.py
    depends_on:
      - postgres_db

volumes:
  pgdata: